### ISSUE TITLE
Create FAQ template, page and collection

### ISSUE THREAD

**Issue by jaywon** [devleague/devleague-website#29]

**Comment by JoeKarlsson1** [comment]
Do we want to control the FAQ's with a collection or should I just put them inline as I have done with the other pages?

**Comment by jaywon** [comment]
FAQ should be a collection so we don't need a developer to add/edit content

**Comment by JoeKarlsson1** [comment]
Got it - I'll make it so.

**Comment by JoeKarlsson1** [comment]
Also - Talking to Jon, I think adding fields might be a better design choice. Are you sure you want it to be a collection? I am under the impression that collections are more for products. Fields are a better choice since they 'live' closer to the page and they can still be changed by an admin from the Airship GUI.

**Comment by jaywon** [comment]
I don't think you can be dynamic in the layout with fields can you? Your
layouts will always have to look for fields by name so new fields means
changes to layout file, unless there's a special field type that's not the
case. Idk, not an Airship pro. I just assume collections is how you deal
with any grouping of items that you don't know how many items you will have
but your layout will support.

Mahalo!

*Jason Sewell*
Curriculum Developer / Co-Founder

*Dev League, LLC*
Phone: (808) 295-6205 :: Email: jason@devleague.com

**Comment by JoeKarlsson1** [comment]
Created page, collection, and added old FAQs from the old DL site to airship. It's still ugly tho - I still need to style it up.
